export module loom.commands.create_moved_to_plugin_command;

import std;
export namespace loom::commands::create_moved_to_plugin_command {
namespace fs = std::filesystem;

struct CommandResponse { bool ok{true}; std::string message; };
[[nodiscard]] inline auto name() -> std::string_view { return "create_moved_to_plugin_command"; }

[[nodiscard]] inline auto run(std::string_view command = {}) -> CommandResponse {
    if (command.empty()) {
        return {.ok = false, .message = "create-moved-to-plugin-command requires a command name"};
    }

    std::string sanitized(command);
    for (char& ch : sanitized) {
        const bool ok = (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
                        (ch >= '0' && ch <= '9') || ch == '-' || ch == '_';
        if (!ok) ch = '-';
    }

    const auto dir = fs::current_path() / ".loom" / "plugin-command-shims";
    std::error_code ec;
    fs::create_directories(dir, ec);
    if (ec) return {.ok = false, .message = "Failed to create shim directory: " + ec.message()};

    const auto path = dir / (sanitized + ".md");
    std::ofstream out(path, std::ios::trunc);
    if (!out) return {.ok = false, .message = "Failed to write shim file: " + path.string()};

    out << "# /" << command << "\n\n";
    out << "This command has moved to a plugin. Install or enable the plugin that owns `/" << command << "`.\n";
    out << "Generated by `/create-moved-to-plugin-command` during the C++ migration.\n";
    out.close();

    return {.ok = true, .message = "Moved-to-plugin command shim written: " + path.string()};
}
}
